apiVersion: apps/v1
kind: Deployment
metadata:
  name: results-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: results
  template:
    metadata:
      labels:
        app: results
    spec:
      containers:
        - name: results
          image: ahmedbahaa2/results:latest
          ports:
            - containerPort: 8081